project:
  type: website
  output-dir: docs

website:
  title: "weblog"
  navbar:
    right:
      - icon: github
        href: https://github.com/loki-veera
      - icon: person-fill
        href: https://loki-veera.github.io/
format:
  html:
    theme: sandstone
    css: styles.css



